# Generated by Django 4.2 on 2023-04-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebook", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="model",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
