# Generated by Django 4.2 on 2023-04-25 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebook", "0002_page_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("site_id", models.CharField(max_length=500)),
                ("site_name", models.CharField(max_length=500)),
                ("site_url", models.URLField()),
            ],
            options={"ordering": ["created_at"], "abstract": False,},
        ),
        migrations.AlterModelOptions(
            name="book", options={"ordering": ["created_at"]},
        ),
        migrations.AlterModelOptions(
            name="page", options={"ordering": ["created_at"]},
        ),
    ]
