# Generated by Django 4.2 on 2023-04-25 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ebook", "0004_site_created_by"),
    ]

    operations = [
        migrations.RemoveField(model_name="book", name="page",),
        migrations.AddField(
            model_name="page",
            name="book",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="ebook.book"
            ),
            preserve_default=False,
        ),
    ]
