# Generated by Django 4.2 on 2023-04-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebook", "0005_remove_book_page_page_book"),
    ]

    operations = [
        migrations.RenameField(
            model_name="page", old_name="swiftxr_link", new_name="site_url",
        ),
        migrations.AddField(
            model_name="page",
            name="site_id",
            field=models.CharField(default=2121, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="page",
            name="site_name",
            field=models.CharField(default="name", max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(name="Site",),
    ]
